const KEY='suivi-classe-v1';
const DEFAULT_BEHAVIORS=[
 {id:crypto.randomUUID(),type:'bonus',emoji:'🙋',label:"Participe à l'oral"},{id:crypto.randomUUID(),type:'bonus',emoji:'🤝',label:'Aide un camarade'},{id:crypto.randomUUID(),type:'bonus',emoji:'🎵',label:'Très bon travail'},{id:crypto.randomUUID(),type:'bonus',emoji:'✅',label:'Matériel prêt'},
 {id:crypto.randomUUID(),type:'malus',emoji:'🗣️',label:'Parle sans lever la main'},{id:crypto.randomUUID(),type:'malus',emoji:'📵',label:'Téléphone sorti'},{id:crypto.randomUUID(),type:'malus',emoji:'🎒',label:'Oubli de matériel'},{id:crypto.randomUUID(),type:'malus',emoji:'💬',label:'Bavardage'}];
let data=load(); let currentClassId=data.classes[0]?.id||null; let tab='class'; let search=''; let todayOnly=false; let sort='name'; let lastEvents=[];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x){x.behaviors??=DEFAULT_BEHAVIORS; x.classes??=[]; x.events??=[]; x.alerts??=[]; return x}}catch(e){} return {classes:[],behaviors:DEFAULT_BEHAVIORS,events:[],alerts:[],theme:'automatic'} }
function save(){localStorage.setItem(KEY,JSON.stringify(data));applyTheme()}
function applyTheme(){let dark=data.theme==='dark'||(data.theme==='automatic'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark)}
function currentClass(){return data.classes.find(c=>c.id===currentClassId)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function avatarColor(name){let n=0;for(const c of name)n=(n*31+c.charCodeAt(0))>>>0;return `hsl(${n%360} 55% 48%)`}
function isToday(d){const a=new Date(d),b=new Date();return a.toDateString()===b.toDateString()}
function eventsFor(id){return data.events.filter(e=>e.studentId===id && (!todayOnly||isToday(e.date)))}
function counts(id){return eventsFor(id).reduce((r,e)=>(e.type==='bonus'?r.bonus++:r.malus++,r),{bonus:0,malus:0})}
function setTab(t){tab=t;render()}
function render(){applyTheme();document.querySelectorAll('.bottom button').forEach(b=>b.classList.remove('active'));document.getElementById('nav-'+tab)?.classList.add('active');document.getElementById('view').innerHTML=tab==='class'?classView():tab==='behaviors'?behaviorView():dataView();}
function classView(){const c=currentClass(); if(!c)return `<div class="panel empty"><div style="font-size:45px">🏫</div><h2>Aucune classe</h2><p>Crée ta première classe pour commencer.</p><button class="primary" onclick="addClass()">➕ Créer une classe</button></div>`;
let total=c.students.reduce((a,s)=>{const k=counts(s.id);return {b:a.b+k.bonus,m:a.m+k.malus}}, {b:0,m:0}); let students=c.students.filter(s=>s.name.toLowerCase().includes(search.toLowerCase()));students.sort((a,b)=>sort==='bonus'?counts(b.id).bonus-counts(a.id).bonus:sort==='malus'?counts(b.id).malus-counts(a.id).malus:a.name.localeCompare(b.name,'fr'));
return `<div class="panel"><div class="row"><select class="grow" onchange="currentClassId=this.value;render()">${data.classes.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button onclick="addClass()">➕ Classe</button><button onclick="openClassSettings()">⚙️</button></div></div>
<div class="grid stats"><div class="stat"><b class="plus">+${total.b}</b><span>Bonus</span></div><div class="stat"><b class="minus">-${total.m}</b><span>Malus</span></div><div class="stat"><b>${total.b-total.m}</b><span>Solde</span></div><div class="stat"><b>${c.students.length}</b><span>Élèves</span></div></div>
<div class="panel"><div class="controls"><input placeholder="🔎 Rechercher un élève…" value="${esc(search)}" oninput="search=this.value;render()"><button onclick="todayOnly=!todayOnly;render()">${todayOnly?'📅 Aujourd’hui':'📊 Total'}</button><button onclick="sort=sort==='name'?'bonus':sort==='bonus'?'malus':'name';render()">↕️ ${sort==='name'?'Nom':sort==='bonus'?'Bonus':'Malus'}</button></div><div class="row" style="margin-top:9px"><button class="primary" onclick="giveAll()">👥 Toute la classe</button><button onclick="addStudents()">➕ Ajouter des élèves</button><button onclick="undo()" ${lastEvents.length?'':'disabled'}>↩️ Annuler</button></div></div>
<div class="grid students">${students.map(studentCard).join('')||'<div class="empty" style="grid-column:1/-1">Aucun élève trouvé.</div>'}</div>`}
function studentCard(s){const k=counts(s.id);return `<article class="student"><div class="avatar" style="background:${avatarColor(s.name)}">${s.photo?`<img src="${s.photo}" alt="">`:initials(s.name)}</div><h3>${esc(s.name)}</h3><div class="score"><span class="plus">+${k.bonus}</span><span class="minus">-${k.malus}</span></div><div class="balance">Solde ${k.bonus-k.malus}</div><div class="actions"><button class="primary" onclick="chooseBehavior('${s.id}','bonus')">➕ Bonus</button><button onclick="chooseBehavior('${s.id}','malus')">➖ Malus</button></div><button style="width:100%;margin-top:7px" onclick="studentMenu('${s.id}')">••• Gérer</button></article>`}
function behaviorView(){return `<div class="panel"><div class="row"><div class="grow"><div class="section-title">Comportements</div><div class="small">Personnalise les boutons utilisés pendant le cours.</div></div><button class="primary" onclick="behaviorForm()">➕ Ajouter</button></div></div>${['bonus','malus'].map(type=>`<div class="panel"><div class="section-title">${type==='bonus'?'🟢 Bonus':'🔴 Malus'}</div>${data.behaviors.filter(b=>b.type===type).map(b=>`<div class="behavior ${type}"><span class="emoji">${b.emoji}</span><span class="grow">${esc(b.label)}</span><button onclick="behaviorForm('${b.id}')">✏️</button><button class="danger" onclick="deleteBehavior('${b.id}')">🗑️</button></div>`).join('')}</div>`).join('')}`}
function dataView(){const c=currentClass();return `<div class="panel"><div class="section-title">💾 Sauvegarde</div><p class="small">Les données restent sur cet iPad. Fais régulièrement une sauvegarde JSON.</p><div class="row"><button class="primary" onclick="backup()">⬇️ Exporter JSON</button><button onclick="document.getElementById('restoreFile').click()">⬆️ Restaurer JSON</button><input id="restoreFile" type="file" accept="application/json,.json" style="display:none" onchange="restoreFile(this.files[0])"><button onclick="copyCSV()">📋 Copier CSV</button><button onclick="window.print()">🖨️ Imprimer</button></div></div><div class="panel"><div class="section-title">📊 Classe active</div>${c?`<p><b>${esc(c.name)}</b> · ${c.students.length} élèves</p>`:'<p class="small">Aucune classe active.</p>'}</div><div class="panel"><div class="section-title">📱 Installation sur iPad</div><p>Dans Safari : <b>Partager → Sur l’écran d’accueil</b>. Une fois installée, l’application peut continuer à fonctionner hors connexion après son premier chargement.</p><p class="small">Pour une vraie installation PWA, l’adresse du site doit être en HTTPS.</p></div><div class="panel danger-zone"><div class="section-title">⚠️ Zone sensible</div><button class="danger" onclick="wipe()">Tout effacer</button></div>`}
function openModal(html){document.getElementById('sheet').innerHTML=html;document.getElementById('modal').classList.add('show')};function closeModal(){document.getElementById('modal').classList.remove('show')};document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function addClass(){openModal(`<h2>Nouvelle classe</h2><input id="mName" placeholder="Nom de la classe" autofocus><textarea id="mStudents" rows="7" placeholder="Un élève par ligne (facultatif)"></textarea><div class="row"><button class="primary" onclick="confirmAddClass()">Créer</button><button onclick="closeModal()">Annuler</button></div>`) }
function confirmAddClass(){const name=document.getElementById('mName').value.trim();if(!name)return toast('Indique un nom de classe');const students=document.getElementById('mStudents').value.split(/\n|;/).map(x=>x.trim()).filter(Boolean).map(name=>({id:uid(),name}));const c={id:uid(),name,students};data.classes.push(c);currentClassId=c.id;save();closeModal();render();}
function addStudents(){openModal(`<h2>Ajouter des élèves</h2><textarea id="mStudents" rows="9" placeholder="Un élève par ligne"></textarea><div class="row"><button class="primary" onclick="confirmAddStudents()">Ajouter</button><button onclick="closeModal()">Annuler</button></div>`) }
function confirmAddStudents(){const c=currentClass();if(!c)return;const names=document.getElementById('mStudents').value.split(/\n|;/).map(x=>x.trim()).filter(Boolean);c.students.push(...names.map(name=>({id:uid(),name})));save();closeModal();render();toast(`${names.length} élève(s) ajouté(s)`)}
function chooseBehavior(studentId,type){const bs=data.behaviors.filter(b=>b.type===type);openModal(`<h2>${type==='bonus'?'➕ Bonus':'➖ Malus'}</h2>${bs.map(b=>`<button style="width:100%;text-align:left;margin:5px 0" onclick="applyBehavior('${studentId}','${b.id}')">${b.emoji} ${esc(b.label)}</button>`).join('')}<button style="width:100%;margin-top:8px" onclick="closeModal()">Annuler</button>`) }
function applyBehavior(studentId,behaviorId){const b=data.behaviors.find(x=>x.id===behaviorId),c=currentClass();if(!b||!c)return;const e={id:uid(),studentId,classId:c.id,behaviorId,type:b.type,label:b.label,emoji:b.emoji,date:new Date().toISOString()};data.events.push(e);lastEvents=[e.id];save();closeModal();render();if(b.type==='malus')checkAlert(studentId);toast(`${b.emoji} ${b.label}`)}
function giveAll(){const c=currentClass();if(!c||!c.students.length)return toast('Aucun élève');openModal(`<h2>Attribuer à toute la classe</h2>${data.behaviors.map(b=>`<button style="width:100%;text-align:left;margin:5px 0" onclick="applyAll('${b.id}')">${b.emoji} ${esc(b.label)}</button>`).join('')}<button style="width:100%;margin-top:8px" onclick="closeModal()">Annuler</button>`) }
function applyAll(behaviorId){const b=data.behaviors.find(x=>x.id===behaviorId),c=currentClass();if(!b||!c)return;lastEvents=[];const now=new Date().toISOString();c.students.forEach(s=>{const e={id:uid(),studentId:s.id,classId:c.id,behaviorId:b.id,type:b.type,label:b.label,emoji:b.emoji,date:now};data.events.push(e);lastEvents.push(e.id);if(b.type==='malus')checkAlert(s.id)});save();closeModal();render();toast(`${b.emoji} appliqué à ${c.students.length} élèves`)}
function checkAlert(studentId){const malus=data.events.filter(e=>e.studentId===studentId&&e.type==='malus');if(malus.length&&malus.length%5===0){const s=currentClass().students.find(x=>x.id===studentId);data.alerts.push({id:uid(),studentId,studentName:s?.name||'',className:currentClass().name,date:new Date().toISOString(),items:malus.slice(-5).map(e=>({date:e.date,label:e.label}))});save();}}
function undo(){if(!lastEvents.length)return;data.events=data.events.filter(e=>!lastEvents.includes(e.id));lastEvents=[];save();render();toast('Dernière action annulée')}
function studentMenu(id){const s=currentClass().students.find(x=>x.id===id);openModal(`<h2>${esc(s.name)}</h2><input id="newName" value="${esc(s.name)}"><div class="row" style="margin-top:9px"><button class="primary" onclick="renameStudent('${id}')">Renommer</button><label class="grow"><button style="width:100%" onclick="document.getElementById('photoInput').click()">📷 Photo</button><input id="photoInput" type="file" accept="image/*" style="display:none" onchange="setPhoto('${id}',this.files[0])"></label></div><button class="danger" style="width:100%;margin-top:8px" onclick="removeStudent('${id}')">🗑️ Supprimer l’élève</button><button style="width:100%;margin-top:8px" onclick="closeModal()">Fermer</button>`)}
function renameStudent(id){const s=currentClass().students.find(x=>x.id===id);s.name=document.getElementById('newName').value.trim()||s.name;save();closeModal();render()}
function removeStudent(id){if(!confirm('Supprimer cet élève et son historique ?'))return;const c=currentClass();c.students=c.students.filter(s=>s.id!==id);data.events=data.events.filter(e=>e.studentId!==id);save();closeModal();render()}
function setPhoto(id,file){if(!file)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const size=320,can=document.createElement('canvas');can.width=can.height=size;const m=Math.min(img.width,img.height);can.getContext('2d').drawImage(img,(img.width-m)/2,(img.height-m)/2,m,m,0,0,size,size);const s=currentClass().students.find(x=>x.id===id);s.photo=can.toDataURL('image/jpeg',.75);save();closeModal();render();toast('Photo enregistrée')};img.src=r.result};r.readAsDataURL(file)}
function openClassSettings(){const c=currentClass();openModal(`<h2>Classe</h2><input id="className" value="${esc(c.name)}"><div class="row" style="margin-top:9px"><button class="primary" onclick="renameClass()">Renommer</button><button onclick="resetClass()">Réinitialiser les compteurs</button></div><button class="danger" style="width:100%;margin-top:8px" onclick="deleteClass()">Supprimer la classe</button><button style="width:100%;margin-top:8px" onclick="closeModal()">Fermer</button>`) }
function renameClass(){const c=currentClass();c.name=document.getElementById('className').value.trim()||c.name;save();closeModal();render()}
function resetClass(){if(!confirm('Effacer tous les bonus/malus de cette classe ?'))return;const c=currentClass();data.events=data.events.filter(e=>e.classId!==c.id);data.alerts=data.alerts.filter(a=>a.className!==c.name);save();closeModal();render();toast('Compteurs réinitialisés')}
function deleteClass(){if(!confirm('Supprimer définitivement cette classe ?'))return;const id=currentClass().id;data.classes=data.classes.filter(c=>c.id!==id);data.events=data.events.filter(e=>e.classId!==id);currentClassId=data.classes[0]?.id||null;save();closeModal();render()}
function behaviorForm(id){const b=id?data.behaviors.find(x=>x.id===id):null;openModal(`<h2>${b?'Modifier':'Nouveau'} comportement</h2><select id="bType"><option value="bonus" ${b?.type==='bonus'?'selected':''}>Bonus</option><option value="malus" ${b?.type==='malus'?'selected':''}>Malus</option></select><input id="bEmoji" value="${esc(b?.emoji||'⭐')}" placeholder="Emoji"><input id="bLabel" value="${esc(b?.label||'')}" placeholder="Libellé"><button class="primary" style="width:100%;margin-top:8px" onclick="saveBehavior('${id||''}')">Enregistrer</button><button style="width:100%;margin-top:8px" onclick="closeModal()">Annuler</button>`) }
function saveBehavior(id){const type=document.getElementById('bType').value,emoji=document.getElementById('bEmoji').value.trim()||'⭐',label=document.getElementById('bLabel').value.trim();if(!label)return toast('Indique un libellé');if(id){const b=data.behaviors.find(x=>x.id===id);Object.assign(b,{type,emoji,label})}else data.behaviors.push({id:uid(),type,emoji,label});save();closeModal();render()}
function deleteBehavior(id){if(!confirm('Supprimer ce comportement ?'))return;data.behaviors=data.behaviors.filter(b=>b.id!==id);data.events=data.events.filter(e=>e.behaviorId!==id);save();render()}
function openSettings(){openModal(`<h2>Réglages</h2><select onchange="data.theme=this.value;save();render()"><option value="automatic" ${data.theme==='automatic'?'selected':''}>Automatique</option><option value="light" ${data.theme==='light'?'selected':''}>Clair</option><option value="dark" ${data.theme==='dark'?'selected':''}>Sombre</option></select><p class="small">Les données sont stockées localement dans le navigateur de l’iPad.</p><button style="width:100%" onclick="closeModal()">Fermer</button>`) }
function toggleTheme(){data.theme=data.theme==='automatic'?'dark':data.theme==='dark'?'light':'automatic';save();render()}
function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='suivi-classe-sauvegarde.json';a.click();URL.revokeObjectURL(a.href);toast('Sauvegarde exportée')}
function restoreFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.classes||!x.events)throw 0;data=x;currentClassId=data.classes[0]?.id||null;save();render();toast('Sauvegarde restaurée')}catch(e){toast('Fichier invalide')}};r.readAsText(file)}
function copyCSV(){const c=currentClass();if(!c)return;let out='Élève;Bonus;Malus;Solde\n';c.students.forEach(s=>{const k=counts(s.id);out+=`"${s.name.replaceAll('"','""')}";${k.bonus};${k.malus};${k.bonus-k.malus}\n`});navigator.clipboard?.writeText(out).then(()=>toast('CSV copié')).catch(()=>{openModal(`<h2>Bilan CSV</h2><textarea rows="12">${esc(out)}</textarea><button style="width:100%;margin-top:8px" onclick="closeModal()">Fermer</button>`)})}
function wipe(){if(!confirm('Effacer toutes les classes, élèves et historiques ?'))return;data={classes:[],behaviors:DEFAULT_BEHAVIORS,events:[],alerts:[],theme:'automatic'};currentClassId=null;save();render()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
